(() => {
 const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const api=(path,data)=>window.FindMeReports.request(path,data);
 let claims=[],active=null,refreshing=false;
 const states={Pending:'รอตรวจคำตอบ',Approved:'อนุมัติแล้ว',Rejected:'ปฏิเสธ',Open:'กำลังคุย / นัดคืน',Handover:'ส่งหลักฐานคืนแล้ว — รอยืนยันรับ',Closed:'รับคืนแล้ว — ปิดเคส'};
 function makeDialog(title){const d=document.createElement('dialog');d.className='item-details-dialog case-dialog';d.innerHTML=`<header class="item-details-head"><h2>${esc(title)}</h2><button type="button" class="btn btn-light" data-close aria-label="ปิด">✕</button></header><div data-body></div>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();
 // Close only when the gesture starts and ends on the backdrop.
 const outside=e=>{const r=d.getBoundingClientRect();return e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom;};
 let backdropPointer=null;
 d.addEventListener('pointerdown',e=>{backdropPointer=e.target===d&&outside(e)?e.pointerId:null;});
 d.addEventListener('pointerup',e=>{const dismiss=backdropPointer===e.pointerId&&e.target===d&&outside(e);backdropPointer=null;if(dismiss)d.close();});
 d.addEventListener('pointercancel',()=>{backdropPointer=null;});d.addEventListener('close',()=>{if(active?.dialog===d)active=null;d.remove();});d.showModal();return d;}
 async function list(){const host=document.getElementById('cloudMyReports');try{claims=(await api('/claims')).claims;window.FindMeMyCases=claims;window.dispatchEvent(new Event('findme-own-reports-updated'));if(!host)return;let box=document.getElementById('claimsBox');if(!box){box=document.createElement('section');box.id='claimsBox';host.after(box);}box.innerHTML='<h2>เคสยืนยันและแชทคืนของ</h2>'+ (claims.length?claims.map(c=>`<article class="form-card case-summary"><h3>${esc(c.item_name)}</h3><p>ผู้แจ้ง: ${esc(c.reporter_name)} • ผู้ขอ: ${esc(c.requester_name)}</p><p>${esc(states[c.status]||c.status)} • ${esc(states[c.case_status]||c.case_status)}</p><p class="case-evidence">${esc(c.evidence)}</p>${c.status==='Rejected'?'<p>คำขอนี้ถูกปฏิเสธ</p>':`<button type="button" class="btn btn-orange" data-open-case="${c.id}">เปิดแชท / ยืนยันรับคืน</button>`}</article>`).join(''):'<p>ยังไม่มีเคส เปิดรายละเอียดของที่พบ แล้วตอบคำถามเพื่อเริ่มเคส</p>');}catch(e){if(host){let p=document.getElementById('caseListError');if(!p){p=document.createElement('p');p.id='caseListError';host.after(p);}p.textContent='โหลดเคสไม่ได้: '+e.message;}}}
 async function start(report,linkedReportId){try{await list();const previous=claims.find(c=>c.report_id===report.id&&!c.can_review);if(previous){if(previous.status==='Rejected')throw new Error('คำขอนี้ถูกปฏิเสธ กรุณาติดต่อผู้แจ้งผ่านช่องทางที่เหมาะสม');return open(previous.id);}const d=makeDialog('ตอบคำถามยืนยันสิ่งของ');d.querySelector('[data-body]').innerHTML=`<p>${esc(report.itemName||report.name)}</p><p>คำตอบส่งให้ผู้แจ้งตรวจสอบก่อนอนุมัติ ไม่ได้ยืนยันอัตโนมัติจากคะแนน</p><form data-answers><label>1. ลักษณะเฉพาะของสิ่งของ<textarea name="detail" required minlength="5" maxlength="700" placeholder="สี ยี่ห้อ รอยตำหนิ สติกเกอร์ หรือของข้างในที่ไม่ได้บอกไว้ในรายงาน"></textarea></label><label>2. วันที่ทำหาย / พบของ<input name="date" type="date" required></label><label>3. สถานที่ที่เห็นครั้งสุดท้าย / พบของ<input name="location" required maxlength="200"></label><label><input name="confirm" type="checkbox" required> ฉันยืนยันว่าข้อมูลเป็นความจริง</label><p role="alert" data-error></p><button class="btn btn-orange" type="submit">ส่งคำตอบและเปิดแชท</button></form>`;d.querySelector('form').onsubmit=async e=>{e.preventDefault();const form=e.target,btn=form.querySelector('[type=submit]');btn.disabled=true;try{const a=Object.fromEntries(new FormData(form));a.confirm=form.elements.confirm.checked;await api('/'+report.id+'/claim',{answers:a,linkedReportId});d.close();await list();const c=claims.find(c=>c.report_id===report.id&&!c.can_review);if(c)await open(c.id);}catch(err){form.querySelector('[data-error]').textContent=err.message;btn.disabled=false;}};}catch(e){alert(e.message);}}
 async function pickFound(id){const own=window.FindMeReports.list().find(r=>r.id===id);const items=window.FindMeReports.list().filter(r=>r.kind==='found'&&!r.isOwner&&r.status!=='Returned'&&(!own||r.category===own.category));const d=makeDialog('I found it — เลือกรายงานของที่พบ');d.querySelector('[data-body]').innerHTML=items.length?items.map(r=>`<article class="case-summary"><b>${esc(r.itemName)}</b><p>ผู้แจ้ง: ${esc(r.reporterName)} • ${esc(r.location)}</p><button class="btn btn-orange" type="button" data-pick="${r.id}">ตอบคำถามยืนยัน</button></article>`).join(''):'<p>ยังไม่มีรายงานของที่พบจากผู้ใช้อื่นในหมวดนี้ ให้ผู้พบของแจ้ง Report Found ก่อน แล้วกลับมาเลือกเพื่อเริ่มเคส</p>';d.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{const r=items.find(r=>r.id===b.dataset.pick);d.close();start(r,id);});}
 async function open(id){const d=makeDialog('แชทและคืนของ');d.querySelector('[data-body]').innerHTML='<p>กำลังโหลดเคส…</p>';active={id,dialog:d};try{await draw(true);}catch(e){d.querySelector('[data-body]').textContent=e.message;}}
 async function draw(initial=false){if(!active||refreshing)return;refreshing=true;const session=active;try{const data=await api('/claims/'+session.id+'/messages');if(active!==session)return;const c=data.case;let body=session.dialog.querySelector('[data-body]');if(initial){body.innerHTML='<div data-info></div><div data-messages class="case-messages" role="log" aria-label="ข้อความในเคส"></div><div data-actions></div><form data-message><label>ข้อความ<textarea name="text" maxlength="2000" placeholder="สอบถามหลักฐานหรือนัดสถานที่คืนของ"></textarea></label><label>แนบรูป<input type="file" name="photo" accept="image/jpeg,image/png,image/webp"></label><p role="alert" data-error></p><button class="btn btn-orange" type="submit">ส่งข้อความ / รูป</button></form>';body.querySelector('[data-message]').onsubmit=async e=>{e.preventDefault();const form=e.target,btn=form.querySelector('button');btn.disabled=true;try{const photo=await window.FindMeReports.photo(form.elements.photo.files[0]);await api('/claims/'+session.id+'/messages',{text:form.elements.text.value,photo});form.reset();await draw();}catch(err){form.querySelector('[data-error]').textContent=err.message;}finally{btn.disabled=false;}};}
 body.querySelector('[data-info]').innerHTML=`<h3>${esc(c.itemName)}</h3><p>ผู้แจ้ง: ${esc(c.reporterName)} • ผู้ขอ: ${esc(c.requesterName)}</p><p>${esc(states[c.status]||c.status)} • ${esc(states[c.caseStatus]||c.caseStatus)}</p><details><summary>คำตอบยืนยัน 3 ข้อ</summary><p class="case-evidence">${esc(c.answers)}</p></details>`;
 const log=body.querySelector('[data-messages]'),nearBottom=log.scrollHeight-log.scrollTop-log.clientHeight<60;const msgs=data.messages.map(m=>`<article class="case-message ${m.mine?'mine':''}"><b>${esc(m.sender_name)}</b><p class="case-evidence">${esc(m.body)}</p>${m.photo?`<img src="${esc(m.photo)}" alt="รูปแนบในเคส">`:''}<small>${esc(new Date(m.created_at).toLocaleString('th-TH'))}</small></article>`).join('')||'<p>ยังไม่มีข้อความ คุยสอบถามหรือนัดคืนของได้ที่นี่</p>';if(log.innerHTML!==msgs){log.innerHTML=msgs;if(nearBottom||initial)log.scrollTop=log.scrollHeight;}
 const actions=body.querySelector('[data-actions]');const actionKey=JSON.stringify([c.status,c.caseStatus,c.canReview,c.role,c.handoverPhoto]);if(actions.dataset.state!==actionKey){actions.dataset.state=actionKey;actions.innerHTML=`${c.canReview&&c.caseStatus!=='Closed'?`<p>ตรวจคำตอบและหลักฐานก่อนอนุมัติ</p><button type="button" class="btn btn-orange" data-approve>คำตอบตรง — อนุมัติเคลม</button> <button type="button" class="btn btn-light" data-reject>ปฏิเสธ / ถอนสิทธิ์</button>`:''}${c.handoverPhoto?`<p>หลักฐานการส่งคืน</p><img class="case-proof" src="${esc(c.handoverPhoto)}" alt="หลักฐานส่งคืนของ">`:''}${c.status==='Approved'&&c.caseStatus!=='Closed'?(c.role==='finder'?'<form data-handover><label>ถ่ายรูป / แนบรูปส่งคืน<input type="file" name="proof" accept="image/jpeg,image/png,image/webp" required></label><button class="btn btn-dark" type="submit">ส่งหลักฐานว่าคืนของแล้ว</button></form>':c.caseStatus==='Handover'?'<button type="button" class="btn btn-dark" data-confirm>ฉันได้รับของแล้ว — ปิดเคส</button>':'<p>รอผู้พบของส่งรูปหลักฐานการคืน แล้วคุณยืนยันรับคืนที่นี่ได้</p>'):''}${c.caseStatus==='Closed'?'<p class="success">ได้รับของคืนแล้ว เคสปิดเรียบร้อย</p>':''}<p role="alert" data-action-error></p>`;
 const act=async(path,payload)=>{try{await api('/claims/'+session.id+path,payload);if(payload.status!=='Rejected')await draw();await list();window.dispatchEvent(new Event('findme-case-updated'));return true;}catch(e){actions.querySelector('[data-action-error]').textContent=e.message;return false;}};
 actions.querySelector('[data-approve]')?.addEventListener('click',()=>act('/review',{status:'Approved'}));actions.querySelector('[data-reject]')?.addEventListener('click',async()=>{if(await act('/review',{status:'Rejected'}))session.dialog.close();});actions.querySelector('[data-confirm]')?.addEventListener('click',()=>{if(confirm('ยืนยันว่าคุณได้รับสิ่งของคืนแล้วจริง ๆ?'))act('/action',{action:'confirm'});});actions.querySelector('[data-handover]')?.addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await act('/action',{action:'handover',photo:await window.FindMeReports.photo(e.target.elements.proof.files[0])});}catch(err){actions.querySelector('[data-action-error]').textContent=err.message;}finally{b.disabled=false;}});}body.querySelector('[data-message]').hidden=c.caseStatus==='Closed';
 }finally{refreshing=false;}}
 document.addEventListener('click',e=>{const startBtn=e.target.closest('[data-start-case]'),chat=e.target.closest('[data-open-case]'),found=e.target.closest('[data-found-my-report]');if(chat)open(chat.dataset.openCase);if(found)pickFound(found.dataset.foundMyReport);if(startBtn){const r=window.FindMeReports.list().find(r=>r.id===startBtn.dataset.startCase);if(r)start(r);}});
 window.FindMeCases={list,start,open};document.addEventListener('DOMContentLoaded',async()=>{await window.FindMeReportsReady;if(window.FindMeUser)list();});setInterval(()=>{if(active&&!document.hidden)draw().catch(e=>{const box=active?.dialog.querySelector('[data-info]');if(box)box.textContent='อัปเดตแชทไม่ได้: '+e.message;});},5000);
})();
