(() => {
 const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let cache=[];
 async function request(path,data){
  const session=JSON.parse(localStorage.getItem('findme_session_v1')||sessionStorage.getItem('findme_session_v1')||'null');
  const res=await fetch(window.FINDME_AUTH_API+'/api/reports'+path,{method:data?'POST':'GET',headers:{Authorization:'Bearer '+(session?.token||''),...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{}),signal:AbortSignal.timeout(30000)});
  const out=await res.json();if(!res.ok)throw new Error(out.error||'บันทึกรายงานไม่สำเร็จ');return out;
 }
 function contactHTML(r){const name=esc(r.reporterName||r.username||'ยังไม่ได้ผูกบัญชี');if(!r.isCloud)return `<p class="meta">ผู้แจ้ง: ${name} — แชร์รายงานเก่าจาก My Reports เพื่อเริ่มเคสในเว็บ</p>`;return `<section class="report-contact"><b>ผู้แจ้ง: ${name}</b><p>ติดต่อและยืนยันรับคืนผ่านแชทในเคส ไม่ต้องแลกข้อมูลติดต่อ</p>${r.isOwner?'<a class="btn btn-light" href="my-reports.html">จัดการเคสใน My Reports</a>':`<button type="button" class="btn btn-orange" data-start-case="${esc(r.id)}">ตอบคำถาม / เปิดเคสและแชท</button>`}</section>`;}
 async function photo(file){
  if(!file)return '';let blob=file;
  if(typeof file==='string'){if(!/^data:image\/(jpeg|png|webp);base64,/.test(file))throw new Error('รูปไม่ถูกต้อง');blob=await(await fetch(file)).blob();}
  if(blob.size>2*1024*1024)throw new Error('รูปใหญ่เกิน 2 MB');
  const image=await createImageBitmap(blob), ratio=Math.min(1,640/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*ratio));canvas.height=Math.max(1,Math.round(image.height*ratio));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);image.close();const result=canvas.toDataURL('image/jpeg',.72);if(result.length>550000)throw new Error('รูปยังใหญ่เกินไป กรุณาเลือกรูปเล็กลง');return result;
 }
 async function create(data){const result=await request('',data);cache=[result.report,...cache.filter(r=>r.id!==result.report.id)];return result.report;}
 window.FindMeReports={list:()=>cache,request,create,contactHTML,photo};
 window.FindMeReportsReady=(async()=>{await window.FindMeAuthReady;if(!window.FindMeUser)return;try{cache=(await request('')).reports;}catch(e){const p=document.createElement('p');p.className='container meta';p.setAttribute('role','alert');p.textContent='โหลดรายงานที่แชร์บนเว็บไม่ได้: '+e.message;document.querySelector('main')?.prepend(p);}})();
 document.addEventListener('click',async e=>{const publish=e.target.closest('[data-publish-old]');if(publish&&document.body.dataset.unifiedReports){try{const r=JSON.parse(localStorage.getItem('kmitl_reports')||'[]').find(r=>String(r.id)===publish.dataset.publishOld);if(r)openContact(r,true);}catch{}return;}const btn=e.target.closest('[data-copy-line]');if(!btn)return;try{await navigator.clipboard.writeText(btn.dataset.copyLine);btn.textContent='คัดลอกแล้ว — เปิด LINE แล้วค้นหา ID นี้';}catch{btn.textContent='LINE ID: '+btn.dataset.copyLine;}});
 document.addEventListener('click',async e=>{const del=e.target.closest('[data-delete-cloud]'),undo=e.target.closest('[data-restore-cloud]');if(!del&&!undo)return;const id=del?.dataset.deleteCloud||undo.dataset.restoreCloud;if(del&&!confirm('ลบประกาศนี้ออกจาก My Reports และ Browse Items? แชทในเคสยังคงอยู่'))return;const b=del||undo;b.disabled=true;try{await request('/'+id+(undo?'/restore':'/delete'),{});const notice=document.getElementById('reportDeleteNotice');if(notice)notice.innerHTML=undo?'<p>คืนประกาศแล้ว</p>':`<p>ลบประกาศแล้ว <button type="button" class="btn btn-light" data-restore-cloud="${esc(id)}">เลิกทำ</button></p>`;await refresh();}catch(err){b.disabled=false;alert(err.message);}});
 async function ownReports(){
  const box=document.getElementById('cloudMyReports');if(!box)return;
  try{const mine=(await request('?mine=1')).reports;window.FindMeOwnReports=mine;if(document.body.dataset.unifiedReports){window.dispatchEvent(new Event('findme-own-reports-updated'));return;}box.innerHTML=mine.length?mine.map(r=>`<article class="form-card" style="margin-bottom:16px"><span class="badge ${r.status==='Returned'?'found':'lost'}">${r.status==='Returned'?'คืนของเรียบร้อย':r.kind==='found'?'พบของ — รอเจ้าของติดต่อ':'กำลังตามหา'}</span><h3>${esc(r.itemName)}</h3>${r.photo?`<img src="${esc(r.photo)}" alt="${esc(r.itemName)}" style="width:100%;max-width:320px;height:180px;object-fit:contain">`:''}<p>${esc(r.category)} • ${esc(r.location)}</p>${contactHTML(r)}<div class="form-actions">${r.status!=='Returned'&&r.kind==='lost'?`<button type="button" class="btn btn-orange" data-found-my-report="${r.id}">I found it — ยืนยันผ่านเคส</button>`:''}<p class="meta">${r.status==='Returned'?'ปิดเคสรับคืนแล้ว':'เปิดคำขอด้านล่างเพื่อคุยและนัดคืนของ'}</p></div></article>`).join(''):'<p class="meta">ยังไม่มีรายงานที่แชร์บนเว็บ แจ้งของใหม่หรือเพิ่มช่องทางติดต่อให้รายงานเก่าด้านล่างได้</p>';
   box.querySelectorAll('[data-edit-contact]').forEach(btn=>btn.addEventListener('click',()=>openContact(mine.find(r=>r.id===btn.dataset.editContact))));
   box.querySelectorAll('[data-return-report]').forEach(btn=>btn.addEventListener('click',async()=>{btn.disabled=true;try{await request('/'+btn.dataset.returnReport+'/status',{status:btn.dataset.nextStatus});await ownReports();}catch(e){btn.disabled=false;const p=document.createElement('p');p.setAttribute('role','alert');p.textContent=e.message;btn.after(p);}}));
  }catch(e){box.textContent='โหลดรายงานไม่ได้: '+e.message;}
 }
 function openContact(report,legacy=false){
  const dialog=document.createElement('dialog');dialog.className='item-details-dialog';dialog.innerHTML=`<form><h2>${legacy?'แชร์รายงานและเพิ่มช่องทางติดต่อ':'แก้ช่องทางติดต่อ'}</h2><p>${esc(report.itemName)}</p><label>ช่องทาง<select name="contactMethod"><option value="inapp">แชทในเว็บ</option><option value="line">LINE ID</option><option value="phone">เบอร์โทร</option><option value="email">อีเมล</option></select></label><label>ข้อมูลติดต่อ<input name="contactValue" maxlength="254" value="${esc(report.contactValue)}"></label><label><input type="checkbox" name="contactConsent" required> ${legacy?'ฉันเป็นผู้แจ้งรายงานนี้ และยอมรับให้สมาชิกเว็บเห็นรูป รายละเอียด และหมุด และเปิดเคสคุยในเว็บ':'ยอมรับให้ใช้แชทในเว็บเพื่อติดต่อคืนของ'}</label><p role="alert" data-error></p><div class="form-actions"><button type="button" class="btn btn-light" data-cancel>ยกเลิก</button><button type="submit" class="btn btn-orange">${legacy?'แชร์รายงาน':'บันทึก'}</button></div></form>`;document.body.append(dialog);dialog.querySelector('select').value='inapp';dialog.querySelector('input[name=contactValue]').closest('label').hidden=true;dialog.querySelector('select').closest('label').hidden=true;dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();
  dialog.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();const form=e.target,btn=form.querySelector('[type=submit]');btn.disabled=true;form.querySelector('[data-error]').textContent='';try{const data=Object.fromEntries(new FormData(form));data.contactConsent=!!form.elements.contactConsent.checked;
   if(legacy){let device=localStorage.getItem('findme_report_device');if(!device){device=crypto.randomUUID();localStorage.setItem('findme_report_device',device);}const shared=await create({...report,...data,kind:report.kind||(report.status==='Submitted'?'found':'lost'),photo:await photo(report.photo),clientKey:device+'_'+report.id});try{const saved=JSON.parse(localStorage.getItem('kmitl_reports')||'[]'),old=saved.find(r=>String(r.id)===String(report.id));if(old){old.sharedReportId=shared.id;localStorage.setItem('kmitl_reports',JSON.stringify(saved));}}catch{}}
   else await request('/'+report.id+'/contact',data);
   if(legacy)document.querySelectorAll('[data-publish-old]').forEach(b=>{if(b.dataset.publishOld===String(report.id)){b.disabled=true;b.textContent='แชร์แล้ว — จัดการในรายงานบนเว็บ';}});
   dialog.close();window.dispatchEvent(new Event('findme-own-reports-updated'));await ownReports();
  }catch(e){form.querySelector('[data-error]').textContent=e.message;btn.disabled=false;}});
 }
 async function refresh(){if(!window.FindMeUser||document.hidden)return;try{const next=(await request('')).reports;if(JSON.stringify(next)!==JSON.stringify(cache)){cache=next;window.dispatchEvent(new Event('findme-reports-updated'));}await ownReports();await window.FindMeCases?.list();}catch(e){const box=document.getElementById('claimsBox');if(box)box.textContent='อัปเดตไม่ได้: '+e.message;}}
 window.addEventListener('focus',refresh);window.addEventListener('findme-case-updated',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});setInterval(refresh,15000);
 document.addEventListener('DOMContentLoaded',async()=>{await window.FindMeReportsReady;if(!window.FindMeUser)return;await ownReports();await window.FindMeCases?.list();const host=document.getElementById('legacyContactReports');if(host){try{const local=JSON.parse(localStorage.getItem('kmitl_reports')||'[]');const remaining=Array.isArray(local)?local.filter(r=>r&&typeof r==='object'&&!r.sharedReportId&&r.status!=='Returned'):[];host.innerHTML=remaining.map(r=>`<p>${esc(r.itemName)} <button type="button" class="btn btn-light" data-publish-old="${esc(r.id)}">แชร์รายงานนี้เพื่อใช้แชทในเว็บ</button></p>`).join('');host.querySelectorAll('[data-publish-old]').forEach(btn=>btn.addEventListener('click',()=>openContact(remaining.find(r=>String(r.id)===btn.dataset.publishOld),true)));}catch{host.textContent='อ่านรายงานเก่าไม่ได้ ข้อมูลเดิมยังอยู่';}}});
})();
